services:
  mysql:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blog-db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  nest-be:
    container_name: nest-be
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    depends_on:
      - mysql
    volumes:
      - ./be:/be/app
      - /be/app/node_modules
    environment:
      DATABASE_URL: mysql://root:password@mysql:3306/blog-db

volumes:
  mysql-data:
